### ISSUE TITLE
Topic: Who is best placed to create the ontology

### ISSUE THREAD

**Issue by RiX012** [opengeospatial/ontology-crs#3]
I would prefer to have an organisation like QUDT (or maybe QUDT itself) to manage the ontology. This due to the fact that it should be very open, but with a central body that oversees versions etc.

Of course the creation can be a different group. But deciding who is going to manage it is probably a good first step.

**Comment by situx** [comment]
Thank you for your suggestion.
Our plan would be that the Open Geospatial Consortium (OGC) would manage the ontology. (Therefore this repository is among the repositories managed by OGC)
The ontology itself is developed in the OGC GeoSemanticsDWG in consultation with the OGC CRS DWG.
Would you think that this is an appropriate context?

**Comment by RiX012** [comment]
Yes, that's exactly what I am looking for.  After some searching this indeed seems the place to be. Last consideration I would add is to write some kind of management plan. To assign the right roles and responsibilities and a have a small roadmap. Nothing to fancy, but just to anchor some basic principles.

**Comment by situx** [comment]
A very short roadmap as of now is:
* Write a publication that outlines the need for a CRS ontology. IF you would like to contribute, feel free to issue a pull request to this repository
* Consulting already existing CRS ontology approaches with the CRS DWG, agree on a namespace at OGC for hosting
A good place to start, as something that is derived from an ISO standard are these ontology models:
https://github.com/ISO-TC211/GOM/tree/master/isotc211_GOM_harmonizedOntology/iso19111/2019
However, they are missing certain items (e.g. projection types) and we need to discuss how to integrate those.

**Comment by RiX012** [comment]
> * IF you would like to contribute, feel free to issue a pull request to this repository

Will do.

> * Consulting already existing CRS ontology approaches with the CRS DWG, agree on a namespace at OGC for hosting
>       A good place to start, as something that is derived from an ISO standard are these ontology models:
>       https://github.com/ISO-TC211/GOM/tree/master/isotc211_GOM_harmonizedOntology/iso19111/2019
>       However, they are missing certain items (e.g. projection types) and we need to discuss how to integrate those.

Looks like an excellent place to start indeed.
